apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rrohxl4hp-python 
  janus-idp.io/tekton: rrohxl4hp-python
  backstage.io/kubernetes-id: rrohxl4hp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rrohxl4hp-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml