apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rrohxl4hp-python-gitops
  description: This is GitOps manifest for rrohxl4hp-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=rrohxl4hp-python
    backstage.io/kubernetes-id: rrohxl4hp-python 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: rrohxl4hp-python-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rrohxl4hp-python
