apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rrohxl4hp-python
  janus-idp.io/tekton: rrohxl4hp-python
  backstage.io/kubernetes-id: rrohxl4hp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rrohxl4hp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
