apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rrohxl4hp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rrohxl4hp-python 
  name: rrohxl4hp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rrohxl4hp-python 
